name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make D=1
    - name: make test
      run: make test
    - name: prepare upload
      run: |
        ls -l > filesizes.out
        mkdir out
        mv *.so *.out out/
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: out
