# SPDX-FileCopyrightText: 2020 knilch <knilch0r@cwde.de>
#
# SPDX-License-Identifier: CC0-1.0

name: codecov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make CFLAGS=--coverage
    - name: make test
      run: make test
    - name: gcov
      run: gcov monoalloc.c
    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true 
